swagger: '2.0'
info:
  title: Tezos RPC
  version: 0.0.1
paths:
  /chains/main/blocks/head/context/big_maps/{big_map_id}/{key_hash}:
    get:
      operationId: getBigMapKey
      produces:
        - application/json
      parameters:
        - in: path
          name: big_map_id
          required: true
          type: integer
        - in: path
          name: key_hash
          required: true
          type: string
      responses:
        '200':
          description: Endpoint for big map keys
          schema:
            type: object
        '404':
          description: Key not found
          schema:
            type: object
        '500':
          description: Internal error
      tags:
        - Big_Map
  /chains/main/blocks/head/context/contracts/{contract}/script:
    get:
      operationId: getContractScript
      produces:
        - application/json
      parameters:
        - in: path
          name: contract
          required: true
          type: string
      responses:
        '200':
          description: Endpoint for contract script
          schema:
            type: object
        '500':
          description: Internal error
      tags:
        - Contracts
  /chains/main/blocks/head/context/contracts/{contract}/storage:
    get:
      operationId: getContractStorage
      produces:
        - application/json
      parameters:
        - in: path
          name: contract
          required: true
          type: string
      responses:
        '200':
          description: Endpoint for contract storage
          schema:
            type: object
        '500':
          description: Internal error
      tags:
        - Contracts
  /chains/main/blocks/head/context/contracts/{contract}/balance:
    get:
      operationId: getContractBalance
      produces:
        - application/json
      parameters:
        - in: path
          name: contract
          required: true
          type: string
      responses:
        '200':
          description: Endpoint for contract balance
          schema:
            type: string
        '500':
          description: Internal error
      tags:
        - Contracts
  /chains/main/blocks/head/context/contracts/{contract}/manager_key:
    get:
      operationId: getContractManagerKey
      produces:
        - application/json
      parameters:
        - in: path
          name: contract
          required: true
          type: string
      responses:
        '200':
          description: Endpoint for contract manager key
          schema:
            type: string
        '500':
          description: Internal error
        '404':
          description: Not found
#        '400':
#          description: Bad Request
#          schema:
#            type: string
      tags:
        - Contracts
  /chains/main/chain_id:
    get:
      operationId: getChaId
      produces:
        - application/json
      responses:
        '200':
          description: Endpoint for chain_id
          schema:
            type: string
        '500':
          description: Internal error
        '404':
          description: Not found
      tags:
        - Chains