version: "3.1"

services:
  api-server:
    build: .
    ports:
      - 9090:9090
    network_mode: "host"
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
  api-documentation:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - 9080:9080