swagger: "2.0"
info:
  title: TezosSign API
  version: 0.0.1

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

paths:
  '/{network}/auth/request':
    post:
      operationId: createAuthRequest
      summary: Create auth request
      produces:
        - application/json
      parameters:
        - in: path
          name: network
          required: true
          type : string
        - in: body
          name: user
          description: The user to create.
          schema:
            $ref: '#/definitions/AuthRequestBody'
      responses:
        '200':
          description: Auth request created
          schema:
            $ref: '#/definitions/AuthRequestResp'
        '400':
          description: Bad request
        '500':
          description: Internal server error
      tags:
        - Auth
  '/{network}/auth':
    post:
      operationId: authBySignedRequest
      summary: Auth by signed request
      produces:
        - application/json
      parameters:
        - in: path
          name: network
          required: true
          type : string
        - in: body
          name: user
          description: Signed request
          schema:
            $ref: '#/definitions/AuthBody'
      responses:
        '200':
          description: Auth tokens
          schema:
            $ref: '#/definitions/AuthResp'
        '400':
          description: Bad request
        '500':
          description: Internal server error
      tags:
        - Auth
  '/{network}/auth/refresh':
    post:
      operationId: refreshAuthTokens
      summary: Refresh auth tokens
      produces:
        - application/json
      parameters:
        - in: path
          name: network
          required: true
          type : string
        - in: body
          name: user
          description: Refresh token
          schema:
            $ref: '#/definitions/RefreshBody'
      responses:
        '200':
          description: Auth tokens
          schema:
            $ref: '#/definitions/RefreshResp'
        '400':
          description: Bad request
        '500':
          description: Internal server error
      tags:
        - Auth
  '/{network}/auth/restore':
    get:
      operationId: restoreAuthTokens
      summary: Restore auth request
      produces:
        - application/json
      parameters:
        - in: path
          name: network
          required: true
          type : string
      responses:
        '200':
          description: Auth request created
          schema:
            $ref: '#/definitions/RestoreResp'
        '400':
          description: Bad request
        '500':
          description: Internal server error
      tags:
        - Auth
  '/{network}/logout':
    get:
      operationId: logout
      summary: Logout request
      produces:
        - application/json
      parameters:
        - in: path
          name: network
          required: true
          type : string
      responses:
        '200':
          description: Logout
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
        '400':
          description: Bad request
        '500':
          description: Internal server error
      tags:
        - Auth
  '/{network}/contract/storage/init':
    post:
      operationId: contractStorageInit
      summary: Contract init storage
      produces:
        - application/json
      security:
        - Bearer: []
      parameters:
        - in: path
          name: network
          required: true
          type : string
        - in: body
          name: user
          schema:
            $ref: '#/definitions/StorageInitBody'
      responses:
        '200':
          description: Contract storage json
          schema:
            type: string
        '400':
          description: Bad request
        '500':
          description: Internal server error
      tags:
        - Contract
  '/{network}/contract/{contract_id}/info':
    get:
      operationId: contractInfo
      summary: Contract init storage
      produces:
        - application/json
      security:
        - Bearer: []
      parameters:
        - in: path
          name: network
          required: true
          type : string
        - in: path
          name: contract_id
          required: true
          type : string
      responses:
        '200':
          description: Contract info
          schema:
            $ref: '#/definitions/ContractInfoResp'
        '400':
          description: Bad request
        '500':
          description: Internal server error
      tags:
        - Contract
  '/{network}/contract/operation':
    post:
      operationId: contractOperation
      summary: Create contract operation
      produces:
        - application/json
      security:
        - Bearer: []
      parameters:
        - in: path
          name: network
          required: true
          type : string
        - in: body
          name: user
          schema:
            $ref: '#/definitions/ContractOperationBody'
      responses:
        '200':
          description: Contract operation
          schema:
            $ref: '#/definitions/ContractOperationResp'
        '400':
          description: Bad request
        '500':
          description: Internal server error
      tags:
        - Contract
  '/{network}/contract/{contract_id}/storage/update':
    post:
      operationId: contractStorageUpdate
      summary: Contract storage update operation
      produces:
        - application/json
      security:
        - Bearer: []
      parameters:
        - in: path
          name: network
          required: true
          type : string
        - in: path
          name: contract_id
          required: true
          type : string
        - in: body
          name: user
          schema:
            $ref: '#/definitions/StorageInitBody'
      responses:
        '200':
          description: Contract update operation
          schema:
            $ref: '#/definitions/ContractOperationResp'
        '400':
          description: Bad request
        '500':
          description: Internal server error
      tags:
        - Contract
  '/{network}/contract/operation/{operation_id}/payload':
    get:
      operationId: buildSignPayload
      summary: Operation payload for sign
      produces:
        - application/json
      security:
        - Bearer: []
      parameters:
        - in: path
          name: network
          required: true
          type : string
        - in: path
          name: operation_id
          required: true
          type : string
      responses:
        '200':
          description: Hexed payload
          schema:
            $ref: '#/definitions/OperationPayloadResp'
        '400':
          description: Bad request
        '500':
          description: Internal server error
      tags:
        - Contract
  '/{network}/contract/operation/{operation_id}/signature':
    post:
      operationId: saveSignedPayload
      summary: Save payload signature
      produces:
        - application/json
      security:
        - Bearer: []
      parameters:
        - in: path
          name: network
          required: true
          type : string
        - in: path
          name: operation_id
          required: true
          type : string
        - in: body
          name: user
          schema:
            $ref: '#/definitions/OperationSignatute'
      responses:
        '200':
          description: Hexed payload
          schema:
            $ref: '#/definitions/OperationSignatureResp'
        '400':
          description: Bad request
        '500':
          description: Internal server error
      tags:
        - Contract
  '/{network}/contract/operation/{operation_id}/build':
    get:
      operationId: buildOperationWithSignatures
      summary: Build operation with signatures
      produces:
        - application/json
      security:
        - Bearer: []
      parameters:
        - in: path
          name: network
          required: true
          type : string
        - in: path
          name: operation_id
          required: true
          type : string
      responses:
        '200':
          description: Hexed payload
          schema:
            $ref: '#/definitions/BuildOperationResp'
        '400':
          description: Bad request
        '500':
          description: Internal server error
      tags:
        - Contract
  '/{network}/contract/{contract_id}/operations':
    get:
      operationId: contractOperations
      summary: Contract operations
      produces:
        - application/json
      security:
        - Bearer: []
      parameters:
        - in: path
          name: network
          required: true
          type : string
        - in: path
          name: contract_id
          required: true
          type : string
      responses:
        '200':
          description: Hexed payload
          schema:
            type: array
            items:
              $ref: '#/definitions/ContractOperationResp'
        '400':
          description: Bad request
        '500':
          description: Internal server error
      tags:
        - Contract
  '/{network}/assets':
    get:
      operationId: assetsList
      summary: Assets list
      produces:
        - application/json
      security:
        - Bearer: []
      parameters:
        - in: path
          name: network
          required: true
          type : string
      responses:
        '200':
          description: Token asset
          schema:
            type: array
            items:
              $ref: '#/definitions/AssetsResp'
        '400':
          description: Bad request
        '500':
          description: Internal server error
      tags:
        - Assets
  '/{network}/assets_rates':
    get:
      operationId: assetsRates
      summary: Assets list
      produces:
        - application/json
      security:
        - Bearer: []
      parameters:
        - in: path
          name: network
          required: true
          type : string
      responses:
        '200':
          description: Assets rates
          schema:
            type: object
        '400':
          description: Bad request
        '500':
          description: Internal server error
      tags:
        - Assets
  '/{network}/contract/{contract_id}/asset':
    post:
      operationId: saveContractAsset
      summary: Save contract asset
      produces:
        - application/json
      security:
        - Bearer: []
      parameters:
        - in: path
          name: network
          required: true
          type : string
        - in: path
          name: contract_id
          required: true
          type : string
        - in: body
          name: asset
          schema:
            $ref: '#/definitions/AssetsResp'
      responses:
        '200':
           description: Contract asset
           schema:
            type: array
            items:
              $ref: '#/definitions/AssetsResp'
        '400':
          description: Bad request
        '500':
          description: Internal server error
      tags:
        - Assets
  '/{network}/contract/{contract_id}/asset/edit':
    post:
      operationId: editContractAsset
      summary: Edit contract asset
      produces:
        - application/json
      security:
        - Bearer: []
      parameters:
        - in: path
          name: network
          required: true
          type : string
        - in: path
          name: contract_id
          required: true
          type : string
        - in: body
          name: asset
          schema:
            $ref: '#/definitions/AssetsResp'
      responses:
        '200':
          description: Contract asset
          schema:
            type: array
            items:
              $ref: '#/definitions/AssetsResp'
        '400':
          description: Bad request
        '500':
          description: Internal server error
      tags:
        - Assets
  '/{network}/contract/{contract_id}/asset/delete':
    post:
      operationId: deleteContractAsset
      summary: Delete contract asset
      produces:
        - application/json
      security:
        - Bearer: []
      parameters:
        - in: path
          name: network
          required: true
          type : string
        - in: path
          name: contract_id
          required: true
          type : string
        - in: body
          name: asset
          schema:
              $ref: '#/definitions/AssetsResp'
      responses:
        '200':
          description: Hexed payload
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
        '400':
          description: Bad request
        '500':
          description: Internal server error
      tags:
        - Assets
  '/{network}/{address}/revealed':
    get:
      operationId: addressRevealed
      summary: Check that address is revealed
      produces:
        - application/json
      security:
        - Bearer: []
      parameters:
        - in: path
          name: network
          required: true
          type : string
        - in: path
          name: address
          required: true
          type : string
      responses:
        '200':
          description: Is revealed
          schema:
            type: object
            properties:
              revealed:
                type: boolean
        '400':
          description: Bad request
        '500':
          description: Internal server error
      tags:
        - Helpers
  '/{network}/exchange_rates':
    get:
      operationId: exchangeRates
      summary: Tezos exchange rates
      produces:
        - application/json
      security:
        - Bearer: []
      parameters:
        - in: path
          name: network
          required: true
          type : string
      responses:
        '200':
          description: Exchange rates
          schema:
            type: array
            items:
              $ref: '#/definitions/ExchangeRatesResp'
        '400':
          description: Bad request
        '500':
          description: Internal server error
      tags:
        - Helpers
definitions:
  AuthRequestBody:
    properties:
      pubkey:
        description: base58 pubkey
        type: string
    required:
      - pubkey
  AuthRequestResp:
    properties:
      token:
        description: auth token for sign
        type: string
    required:
      - token
  AuthBody:
    properties:
      payload:
        type: string
      pub_key:
        type: string
      signature:
        type: string
    required:
      - payload
      - pub_key
      - signature
  AuthResp:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    required:
      - access_token
      - refresh_token
  RefreshBody:
    properties:
      refresh_token:
        type: string
    required:
      - refresh_token
  RefreshResp:
    $ref: '#/definitions/AuthResp'
  RestoreResp:
    $ref: '#/definitions/AuthResp'
  StorageInitBody:
    properties:
      threshold:
        type: integer
      entities:
        type: array
        items:
          type: string
    required:
      - threshold
      - entities
  Owner:
    properties:
      pub_key:
        type: string
      address:
        type: string
  ContractInfoResp:
    properties:
      address:
        type: string
      balance:
        type: integer
      threshold:
        type: integer
      counter:
        type: integer
      owners:
        type: array
        items:
          $ref: '#/definitions/Owner'
  ContractOperationBody:
    properties:
      contract_id:
        type: string
      type:
        type: string
      amount:
        type: integer
      to:
        type: string
      from:
        type: string
      asset_id:
        type: string
      # Custom michelson bytes or JSON payload
      custom_payload:
        type: string
    required:
      - contract_id
  ContractOperationResp:
    properties:
      operation_id:
        type: string
      nonce:
        type: integer
      status:
        type: string
      created_at:
        type: integer
      operation_info:
        $ref: '#/definitions/ContractOperationBody'
      network_id:
        type: string
  OperationPayloadResp:
    properties:
      operation_id:
        type: string
      payload:
        type: string
  OperationSignatute:
    properties:
      contract_id:
        type: string
      type:
        type: string
      pub_key:
        type: string
      signature:
        type: string
  OperationSignatureResp:
    properties:
      sig_count:
        type: integer
      threshold:
        type: integer
  BuildOperationResp:
    properties:
      entrypoint:
        type: string
      value:
        type: string
  AssetsResp:
    properties:
      name:
        type: string
      contract_type:
        type: string
      address:
        type: string
      dexter_address:
        type: string
      scale:
        type: integer
      ticker:
        type: string
      is_global:
        type: boolean
  ExchangeRatesResp:
    properties:
      btc:
        type: string
      eur:
        type: string
      usd:
        type: string
      cny:
        type: string
      jpy:
        type: string
      krw:
        type: string